# coding: utf-8

# flake8: noqa

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from fireflyiii_client.api_client import ApiClient

# import Configuration
from fireflyiii_client.configuration import Configuration

# import exceptions
from fireflyiii_client.exceptions import OpenApiException
from fireflyiii_client.exceptions import ApiAttributeError
from fireflyiii_client.exceptions import ApiTypeError
from fireflyiii_client.exceptions import ApiValueError
from fireflyiii_client.exceptions import ApiKeyError
from fireflyiii_client.exceptions import ApiException
