# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fireflyiii_client import schemas  # noqa: F401


class ConfigValueFilter(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    @schemas.classproperty
    def CONFIGURATION_IS_DEMO_SITE(cls):
        return cls("configuration.is_demo_site")
    
    @schemas.classproperty
    def CONFIGURATION_PERMISSION_UPDATE_CHECK(cls):
        return cls("configuration.permission_update_check")
    
    @schemas.classproperty
    def CONFIGURATION_LAST_UPDATE_CHECK(cls):
        return cls("configuration.last_update_check")
    
    @schemas.classproperty
    def CONFIGURATION_SINGLE_USER_MODE(cls):
        return cls("configuration.single_user_mode")
    
    @schemas.classproperty
    def FIREFLY_VERSION(cls):
        return cls("firefly.version")
    
    @schemas.classproperty
    def FIREFLY_API_VERSION(cls):
        return cls("firefly.api_version")
    
    @schemas.classproperty
    def FIREFLY_DEFAULT_LOCATION(cls):
        return cls("firefly.default_location")
    
    @schemas.classproperty
    def FIREFLY_ACCOUNT_TO_TRANSACTION(cls):
        return cls("firefly.account_to_transaction")
    
    @schemas.classproperty
    def FIREFLY_ALLOWED_OPPOSING_TYPES(cls):
        return cls("firefly.allowed_opposing_types")
    
    @schemas.classproperty
    def FIREFLY_ACCOUNT_ROLES(cls):
        return cls("firefly.accountRoles")
    
    @schemas.classproperty
    def FIREFLY_VALID_LIABILITIES(cls):
        return cls("firefly.valid_liabilities")
    
    @schemas.classproperty
    def FIREFLY_INTEREST_PERIODS(cls):
        return cls("firefly.interest_periods")
    
    @schemas.classproperty
    def FIREFLY_ENABLE_EXTERNAL_MAP(cls):
        return cls("firefly.enable_external_map")
    
    @schemas.classproperty
    def FIREFLY_EXPECTED_SOURCE_TYPES(cls):
        return cls("firefly.expected_source_types")
    
    @schemas.classproperty
    def APP_TIMEZONE(cls):
        return cls("app.timezone")
    
    @schemas.classproperty
    def FIREFLY_BILL_PERIODS(cls):
        return cls("firefly.bill_periods")
    
    @schemas.classproperty
    def FIREFLY_CREDIT_CARD_TYPES(cls):
        return cls("firefly.credit_card_types")
    
    @schemas.classproperty
    def FIREFLY_LANGUAGES(cls):
        return cls("firefly.languages")
    
    @schemas.classproperty
    def FIREFLY_VALID_VIEW_RANGES(cls):
        return cls("firefly.valid_view_ranges")
