# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fireflyiii_client import schemas  # noqa: F401


class DataDestroyObject(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    @schemas.classproperty
    def BUDGETS(cls):
        return cls("budgets")
    
    @schemas.classproperty
    def BILLS(cls):
        return cls("bills")
    
    @schemas.classproperty
    def PIGGY_BANKS(cls):
        return cls("piggy_banks")
    
    @schemas.classproperty
    def RULES(cls):
        return cls("rules")
    
    @schemas.classproperty
    def RECURRING(cls):
        return cls("recurring")
    
    @schemas.classproperty
    def CATEGORIES(cls):
        return cls("categories")
    
    @schemas.classproperty
    def TAGS(cls):
        return cls("tags")
    
    @schemas.classproperty
    def OBJECT_GROUPS(cls):
        return cls("object_groups")
    
    @schemas.classproperty
    def ACCOUNTS(cls):
        return cls("accounts")
    
    @schemas.classproperty
    def ASSET_ACCOUNTS(cls):
        return cls("asset_accounts")
    
    @schemas.classproperty
    def EXPENSE_ACCOUNTS(cls):
        return cls("expense_accounts")
    
    @schemas.classproperty
    def REVENUE_ACCOUNTS(cls):
        return cls("revenue_accounts")
    
    @schemas.classproperty
    def LIABILITIES(cls):
        return cls("liabilities")
    
    @schemas.classproperty
    def TRANSACTIONS(cls):
        return cls("transactions")
    
    @schemas.classproperty
    def WITHDRAWALS(cls):
        return cls("withdrawals")
    
    @schemas.classproperty
    def DEPOSITS(cls):
        return cls("deposits")
    
    @schemas.classproperty
    def TRANSFERS(cls):
        return cls("transfers")
