# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_accounts_id.delete import DeleteAccount
from fireflyiii_client.paths.api_v1_accounts_id.get import GetAccount
from fireflyiii_client.paths.api_v1_accounts.get import ListAccount
from fireflyiii_client.paths.api_v1_accounts_id_attachments.get import ListAttachmentByAccount
from fireflyiii_client.paths.api_v1_accounts_id_piggy_banks.get import ListPiggyBankByAccount
from fireflyiii_client.paths.api_v1_accounts_id_transactions.get import ListTransactionByAccount
from fireflyiii_client.paths.api_v1_accounts.post import StoreAccount
from fireflyiii_client.paths.api_v1_accounts_id.put import UpdateAccount


class AccountsApi(
    DeleteAccount,
    GetAccount,
    ListAccount,
    ListAttachmentByAccount,
    ListPiggyBankByAccount,
    ListTransactionByAccount,
    StoreAccount,
    UpdateAccount,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
