# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_autocomplete_accounts.get import GetAccountsAc
from fireflyiii_client.paths.api_v1_autocomplete_bills.get import GetBillsAc
from fireflyiii_client.paths.api_v1_autocomplete_budgets.get import GetBudgetsAc
from fireflyiii_client.paths.api_v1_autocomplete_categories.get import GetCategoriesAc
from fireflyiii_client.paths.api_v1_autocomplete_currencies.get import GetCurrenciesAc
from fireflyiii_client.paths.api_v1_autocomplete_currencies_with_code.get import GetCurrenciesCodeAc
from fireflyiii_client.paths.api_v1_autocomplete_object_groups.get import GetObjectGroupsAc
from fireflyiii_client.paths.api_v1_autocomplete_piggy_banks.get import GetPiggiesAc
from fireflyiii_client.paths.api_v1_autocomplete_piggy_banks_with_balance.get import GetPiggiesBalanceAc
from fireflyiii_client.paths.api_v1_autocomplete_recurring.get import GetRecurringAc
from fireflyiii_client.paths.api_v1_autocomplete_rule_groups.get import GetRuleGroupsAc
from fireflyiii_client.paths.api_v1_autocomplete_rules.get import GetRulesAc
from fireflyiii_client.paths.api_v1_autocomplete_tags.get import GetTagAc
from fireflyiii_client.paths.api_v1_autocomplete_transaction_types.get import GetTransactionTypesAc
from fireflyiii_client.paths.api_v1_autocomplete_transactions.get import GetTransactionsAc
from fireflyiii_client.paths.api_v1_autocomplete_transactions_with_id.get import GetTransactionsIdac


class AutocompleteApi(
    GetAccountsAc,
    GetBillsAc,
    GetBudgetsAc,
    GetCategoriesAc,
    GetCurrenciesAc,
    GetCurrenciesCodeAc,
    GetObjectGroupsAc,
    GetPiggiesAc,
    GetPiggiesBalanceAc,
    GetRecurringAc,
    GetRuleGroupsAc,
    GetRulesAc,
    GetTagAc,
    GetTransactionTypesAc,
    GetTransactionsAc,
    GetTransactionsIdac,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
