# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_currencies_code_default.post import DefaultCurrency
from fireflyiii_client.paths.api_v1_currencies_code.delete import DeleteCurrency
from fireflyiii_client.paths.api_v1_currencies_code_disable.post import DisableCurrency
from fireflyiii_client.paths.api_v1_currencies_code_enable.post import EnableCurrency
from fireflyiii_client.paths.api_v1_currencies_code.get import GetCurrency
from fireflyiii_client.paths.api_v1_currencies_default.get import GetDefaultCurrency
from fireflyiii_client.paths.api_v1_currencies_code_accounts.get import ListAccountByCurrency
from fireflyiii_client.paths.api_v1_currencies_code_available_budgets.get import ListAvailableBudgetByCurrency
from fireflyiii_client.paths.api_v1_currencies_code_bills.get import ListBillByCurrency
from fireflyiii_client.paths.api_v1_currencies_code_budget_limits.get import ListBudgetLimitByCurrency
from fireflyiii_client.paths.api_v1_currencies.get import ListCurrency
from fireflyiii_client.paths.api_v1_currencies_code_recurrences.get import ListRecurrenceByCurrency
from fireflyiii_client.paths.api_v1_currencies_code_rules.get import ListRuleByCurrency
from fireflyiii_client.paths.api_v1_currencies_code_transactions.get import ListTransactionByCurrency
from fireflyiii_client.paths.api_v1_currencies.post import StoreCurrency
from fireflyiii_client.paths.api_v1_currencies_code.put import UpdateCurrency


class CurrenciesApi(
    DefaultCurrency,
    DeleteCurrency,
    DisableCurrency,
    EnableCurrency,
    GetCurrency,
    GetDefaultCurrency,
    ListAccountByCurrency,
    ListAvailableBudgetByCurrency,
    ListBillByCurrency,
    ListBudgetLimitByCurrency,
    ListCurrency,
    ListRecurrenceByCurrency,
    ListRuleByCurrency,
    ListTransactionByCurrency,
    StoreCurrency,
    UpdateCurrency,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
