# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_data_bulk_transactions.post import BulkUpdateTransactions
from fireflyiii_client.paths.api_v1_data_destroy.delete import DestroyData
from fireflyiii_client.paths.api_v1_data_export_accounts.get import ExportAccounts
from fireflyiii_client.paths.api_v1_data_export_bills.get import ExportBills
from fireflyiii_client.paths.api_v1_data_export_budgets.get import ExportBudgets
from fireflyiii_client.paths.api_v1_data_export_categories.get import ExportCategories
from fireflyiii_client.paths.api_v1_data_export_piggy_banks.get import ExportPiggies
from fireflyiii_client.paths.api_v1_data_export_recurring.get import ExportRecurring
from fireflyiii_client.paths.api_v1_data_export_rules.get import ExportRules
from fireflyiii_client.paths.api_v1_data_export_tags.get import ExportTags
from fireflyiii_client.paths.api_v1_data_export_transactions.get import ExportTransactions


class DataApi(
    BulkUpdateTransactions,
    DestroyData,
    ExportAccounts,
    ExportBills,
    ExportBudgets,
    ExportCategories,
    ExportPiggies,
    ExportRecurring,
    ExportRules,
    ExportTags,
    ExportTransactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
