# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_insight_expense_asset.get import InsightExpenseAsset
from fireflyiii_client.paths.api_v1_insight_expense_bill.get import InsightExpenseBill
from fireflyiii_client.paths.api_v1_insight_expense_budget.get import InsightExpenseBudget
from fireflyiii_client.paths.api_v1_insight_expense_category.get import InsightExpenseCategory
from fireflyiii_client.paths.api_v1_insight_expense_expense.get import InsightExpenseExpense
from fireflyiii_client.paths.api_v1_insight_expense_no_bill.get import InsightExpenseNoBill
from fireflyiii_client.paths.api_v1_insight_expense_no_budget.get import InsightExpenseNoBudget
from fireflyiii_client.paths.api_v1_insight_expense_no_category.get import InsightExpenseNoCategory
from fireflyiii_client.paths.api_v1_insight_expense_no_tag.get import InsightExpenseNoTag
from fireflyiii_client.paths.api_v1_insight_expense_tag.get import InsightExpenseTag
from fireflyiii_client.paths.api_v1_insight_expense_total.get import InsightExpenseTotal
from fireflyiii_client.paths.api_v1_insight_income_asset.get import InsightIncomeAsset
from fireflyiii_client.paths.api_v1_insight_income_category.get import InsightIncomeCategory
from fireflyiii_client.paths.api_v1_insight_income_no_category.get import InsightIncomeNoCategory
from fireflyiii_client.paths.api_v1_insight_income_no_tag.get import InsightIncomeNoTag
from fireflyiii_client.paths.api_v1_insight_income_revenue.get import InsightIncomeRevenue
from fireflyiii_client.paths.api_v1_insight_income_tag.get import InsightIncomeTag
from fireflyiii_client.paths.api_v1_insight_income_total.get import InsightIncomeTotal
from fireflyiii_client.paths.api_v1_insight_transfer_category.get import InsightTransferCategory
from fireflyiii_client.paths.api_v1_insight_transfer_no_category.get import InsightTransferNoCategory
from fireflyiii_client.paths.api_v1_insight_transfer_no_tag.get import InsightTransferNoTag
from fireflyiii_client.paths.api_v1_insight_transfer_tag.get import InsightTransferTag
from fireflyiii_client.paths.api_v1_insight_transfer_total.get import InsightTransferTotal
from fireflyiii_client.paths.api_v1_insight_transfer_asset.get import InsightTransfers


class InsightApi(
    InsightExpenseAsset,
    InsightExpenseBill,
    InsightExpenseBudget,
    InsightExpenseCategory,
    InsightExpenseExpense,
    InsightExpenseNoBill,
    InsightExpenseNoBudget,
    InsightExpenseNoCategory,
    InsightExpenseNoTag,
    InsightExpenseTag,
    InsightExpenseTotal,
    InsightIncomeAsset,
    InsightIncomeCategory,
    InsightIncomeNoCategory,
    InsightIncomeNoTag,
    InsightIncomeRevenue,
    InsightIncomeTag,
    InsightIncomeTotal,
    InsightTransferCategory,
    InsightTransferNoCategory,
    InsightTransferNoTag,
    InsightTransferTag,
    InsightTransferTotal,
    InsightTransfers,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
