# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_link_types_id.delete import DeleteLinkType
from fireflyiii_client.paths.api_v1_transaction_links_id.delete import DeleteTransactionLink
from fireflyiii_client.paths.api_v1_link_types_id.get import GetLinkType
from fireflyiii_client.paths.api_v1_transaction_links_id.get import GetTransactionLink
from fireflyiii_client.paths.api_v1_link_types.get import ListLinkType
from fireflyiii_client.paths.api_v1_link_types_id_transactions.get import ListTransactionByLinkType
from fireflyiii_client.paths.api_v1_transaction_links.get import ListTransactionLink
from fireflyiii_client.paths.api_v1_link_types.post import StoreLinkType
from fireflyiii_client.paths.api_v1_transaction_links.post import StoreTransactionLink
from fireflyiii_client.paths.api_v1_link_types_id.put import UpdateLinkType
from fireflyiii_client.paths.api_v1_transaction_links_id.put import UpdateTransactionLink


class LinksApi(
    DeleteLinkType,
    DeleteTransactionLink,
    GetLinkType,
    GetTransactionLink,
    ListLinkType,
    ListTransactionByLinkType,
    ListTransactionLink,
    StoreLinkType,
    StoreTransactionLink,
    UpdateLinkType,
    UpdateTransactionLink,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
