# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_object_groups_id.delete import DeleteObjectGroup
from fireflyiii_client.paths.api_v1_object_groups_id.get import GetObjectGroup
from fireflyiii_client.paths.api_v1_object_groups_id_bills.get import ListBillByObjectGroup
from fireflyiii_client.paths.api_v1_object_groups.get import ListObjectGroups
from fireflyiii_client.paths.api_v1_object_groups_id_piggy_banks.get import ListPiggyBankByObjectGroup
from fireflyiii_client.paths.api_v1_object_groups_id.put import UpdateObjectGroup


class ObjectGroupsApi(
    DeleteObjectGroup,
    GetObjectGroup,
    ListBillByObjectGroup,
    ListObjectGroups,
    ListPiggyBankByObjectGroup,
    UpdateObjectGroup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
