# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_rule_groups_id.delete import DeleteRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups_id_trigger.post import FireRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups_id.get import GetRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups_id_rules.get import ListRuleByGroup
from fireflyiii_client.paths.api_v1_rule_groups.get import ListRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups.post import StoreRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups_id_test.get import TestRuleGroup
from fireflyiii_client.paths.api_v1_rule_groups_id.put import UpdateRuleGroup


class RuleGroupsApi(
    DeleteRuleGroup,
    FireRuleGroup,
    GetRuleGroup,
    ListRuleByGroup,
    ListRuleGroup,
    StoreRuleGroup,
    TestRuleGroup,
    UpdateRuleGroup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
