# coding: utf-8

"""
    Firefly III API v1.5.6

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00   # noqa: E501

    The version of the OpenAPI document: 1.5.6
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

from fireflyiii_client.paths.api_v1_webhooks_id.delete import DeleteWebhook
from fireflyiii_client.paths.api_v1_webhooks_id_messages_message_id.delete import DeleteWebhookMessage
from fireflyiii_client.paths.api_v1_webhooks_id_messages_message_id_attempts_attempt_id.delete import DeleteWebhookMessageAttempt
from fireflyiii_client.paths.api_v1_webhooks_id_messages_message_id.get import GetSingleWebhookMessage
from fireflyiii_client.paths.api_v1_webhooks_id_messages_message_id_attempts_attempt_id.get import GetSingleWebhookMessageAttempt
from fireflyiii_client.paths.api_v1_webhooks_id.get import GetWebhook
from fireflyiii_client.paths.api_v1_webhooks_id_messages_message_id_attempts.get import GetWebhookMessageAttempts
from fireflyiii_client.paths.api_v1_webhooks_id_messages.get import GetWebhookMessages
from fireflyiii_client.paths.api_v1_webhooks.get import ListWebhook
from fireflyiii_client.paths.api_v1_webhooks.post import StoreWebhook
from fireflyiii_client.paths.api_v1_webhooks_id_submit.post import SubmitWebook
from fireflyiii_client.paths.api_v1_webhooks_id.put import UpdateWebhook


class WebhooksApi(
    DeleteWebhook,
    DeleteWebhookMessage,
    DeleteWebhookMessageAttempt,
    GetSingleWebhookMessage,
    GetSingleWebhookMessageAttempt,
    GetWebhook,
    GetWebhookMessageAttempts,
    GetWebhookMessages,
    ListWebhook,
    StoreWebhook,
    SubmitWebook,
    UpdateWebhook,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
